# Generated by Django 3.2 on 2021-05-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morphserverapp', '0015_alter_pdb_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morphrequest',
            name='auto_interpolation',
        ),
        migrations.RemoveField(
            model_name='morphrequest',
            name='morphing_count',
        ),
        migrations.AddField(
            model_name='morphrequest',
            name='saved_counts',
            field=models.JSONField(default=''),
        ),
    ]
