# Generated by Django 3.2 on 2021-05-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morphserverapp', '0016_auto_20210512_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morphrequest',
            name='saved_counts',
        ),
    ]
